# Generated by Django 6.0.5 on 2026-05-26 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('detalle_proyectos', models.JSONField(default=list)),
                ('total_ahorro_proyectos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_facturado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facturacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_id', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='facturacion.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'proyecto_id')},
            },
        ),
    ]
